config/routes.rb
Rails.application.routes.draw do

  match "/users/sign_up" => redirect("/users/sign_in"), via: [:get, :post] if Rails.env.production?
  devise_for :users
  root to: 'articles#index'

  get '/tags' => 'welcome#tags'
  get '/archive' => 'welcome#archive'
  get '/album' => 'welcome#album'
  get '/about' => 'welcome#about'

  resources :articles do
    collection do
      get 'more'
    end
  end
  resources :categories, only: [:index]

  get 'locale' => 'application#locale'
  namespace :admin do 
    resources :articles
    resources :categories
  end
  get '*path' => 'application#render_404'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  validates :title, presence: true

  delegate :email, to: "author", prefix: :author, allow_nil: true

  acts_as_taggable
  paginates_per Settings.paginates.per_page

  default_scope -> { order(id: :desc) }
  scope :published, -> { where(published: true) }

  class << self
    def query(params)
      result = self.all
      result = result.where(category_id: params[:category_id]) if params[:category_id].present?
      result = result.where("title like ? OR body LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%") if params[:q].present?
      result = result.joins(:tags).where("tags.name = ?", params[:tag]) if params[:tag].present?
      if params[:pub_date].present?
        date = DateTime.parse(params[:pub_date].gsub(/-/, '/'))
        result = result.where("created_at BETWEEN ? AND ?", date.beginning_of_month, date.end_of_month)
      end
      result = result.offset(params[:offset].to_i) if params[:offset].present?
      result
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true, uniqueness: true

  paginates_per Settings.paginates.per_page
  mount_uploader :image, CategoryImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles, foreign_key: :author_id
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_action :set_article, only: [:edit, :update, :destroy]
  def index
    @articles = Article.query(params).page(params[:page] || 1)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article saved."
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      flash[:success] = "Article Updated."
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @article.update_attributes(published: false)
    flash[:success] = 'Article unpublished.'
    redirect_to action: :index
  end

  protected
  def article_params
    params.require(:article).permit(:title, :body, :category_id, :published, :tag_list)
  end
  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:edit, :update, :destroy]
  def index
    @categories = Category.page(params[:page] || 1)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category saved.'
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Category updated.'
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = 'Category destroyed.'
    redirect_to action: :index
  end

  protected
  def category_params
    params.require(:category).permit(:name, :image)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin/application'
  before_action :check_authority

  protected
  def check_authority
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def render_404
    render 'errors/404'
  end

  def locale
    locale = params[:locale]
    session[:locale] = locale if locale
    redirect_to :back
  rescue => _
    redirect_to :back
  end

  protected
  def set_locale
    I18n.locale = session[:locale]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  def index
    @articles = Article.includes(:category).query(params).published.page(params[:page] || 1)
  end

  def show
  end

  protected
  def set_article
    @article = Article.where(published: true).find(params[:id])
  rescue ActiveRecord::RecordNotFound => _
    render_404
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Rails.cache.fetch("all_categories", expires_in: 1.hour) do 
      Category.includes(:articles).all
    end
    @row_count = 4
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def tags
  end

  def album
  end

  def archive
  end

  def about
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
  def categories_for_select
    Rails.cache.fetch("categories_for_select", expires_in: 1.hours) do
      categories = [['请选择', 0]]
      Category.select("id, name").all.each do |cate|
        categories << [cate.name, cate.id]
      end
      categories
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    if params[:controller] == path 
      "active"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def all_tags
    Rails.cache.fetch("all_tags_for_show", expires_in: 1.hours) do
      ActsAsTaggableOn::Tag.all
    end
  end

  def articles_count_of_tag(ta)
    Rails.cache.fetch("articles_count_of_tag", expires_in: 5.minutes) do 
      article_ids = ActsAsTaggableOn::Tagging.where(tag_id: ta.id, taggable_type: "Article").pluck(:taggable_id)
      Article.published.where(id: article_ids).count
    end
  end

  def tag_color(tag_m)
    idx = tag_m.present? ? (tag_m.taggings_count % 4) : 0
    colors[idx]
  end

  def colors
    ["success", "warning", "danger", "info"]
  end

  def archive_dates
    Rails.cache.fetch("archive_dates", expires_in: 1.hours) do 
      ActiveRecord::Base.connection.exec_query("SELECT date_format(created_at, '%Y-%m') AS created_at, count(*) AS cnt FROM articles WHERE published = true GROUP BY date_format(created_at, '%Y-%m') ORDER BY created_at DESC;")
    end
  end
end

app/views/admin/articles/_form.html.erb
<div class="example">
  <%= form_for [:admin, @article] do |f| %>
    <%= render 'errors/form_error', model: @article %>
    <div class="grid">
      <%= f.label :title %>
      <div class="input-control text full-size">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="grid">
      <%= f.label :category %>
      <div class="input-control select">
        <%= f.select :category_id, categories_for_select %>
      </div>
    </div>
    <div class="grid">
      <%= f.label :body %>
      <div class="input-control textarea full-size">
        <%= f.text_area :body %>
      </div>
    </div>
    <div class="grid">
      <%= f.label :tags %>
      <div class="input-control text full-size">
        <%= f.text_field :tag_list, value: @article.tag_list.join(",") %>
      </div>
    </div>
    <div class="grid">
      <%= f.label :published %>
      <%= f.check_box :published %>
    </div>
    <div class="grid">
      <%= f.submit %>
    </div>
  <% end %>
</div>

<script>
$(function() {
  $("#article_tag_list").tagsInput({
    width: 'auto',
    height: 'auto'
  });
  editor = new Simditor({
    textarea: $("#article_body"),
  });
  //var converter = Markdown.getSanitizingConverter();
  //var editor = new Markdown.Editor(converter);
  //editor.run();
});
</script>

app/views/admin/articles/index.html.erb
<h1 class="text-light"><%= t('activerecord.models.article') %></h1>
<hr class="thin bg-grayLighter">
<a class="button primary" href="<%= new_admin_article_path %>">
  <span class="mif-plus"></span>
  Create...
</a>
<%= paginate @articles %>
<hr class="thin bg-grayLighter"></hr>
<% if @articles.any? %>
  <div class="dataTables_wrapper no-footer">
    <table class="dataTable border bordered no-footer" data-auto-width="false" data-role="" role="grid" aria-describedby="">
      <thead>
        <tr role="row">
          <td style="width: 20px" tabindex="0">ID</td>
          <td>Title</td>
          <td>Body</td>
          <td>Published</td>
          <td>Created At</td>
          <td>Updated At</td>
          <td>Operation</td>
        </tr>
      </thead>
      <tbody>
        <% @articles.each_with_index do |art, idx| %>
          <tr class="<%= idx % 2 == 1 ? 'odd' : 'even' %>" role="row">
            <td><%= art.id %></td>
            <td><%= art.title %></td>
            <td><%= truncate(strip_tags(art.body), length: 10) %></td>
            <td class="align-center"><span class="<%= (art.published ? "mif-checkmark fg-green" : "mif-stop fg-red").html_safe %>"></span></td>
            <td><%= art.created_at.to_s(:db) %></td>
            <td><%= art.updated_at.to_s(:db) %></td>
            <td>
              <%= link_to "Edit", edit_admin_article_path(art) %>
              <%= link_to "Destroy", [:admin, art], method: :delete, data: {confirm: 'Are you sure?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div>
    Sorry, there is no data.
  </div>
<% end %>
<%= paginate @articles %>

app/views/admin/categories/_form.html.erb
<div class="example">
  <%= render 'errors/form_error', model: @category %>
  <%= form_for [:admin, @category] do |f| %>
    <div class="grid">
      <%= f.label :name %>
      <div class="input-control text full-size">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="grid">
      <%= f.label :image %>
      <div class="input-control file full-size" data-role='input'>
        <%= f.file_field :image %>
        <button class="button">
          <span class="mif-folder"></span>
        </button>
      </div>
      <%= image_tag(@category.image_url(:thumb)) if @category.image.present? %>
    </div>
    <div class="grid">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1 class="text-light"><%= t('activerecord.models.category') %></h1>
<hr class="thin bg-grayLighter">
<a class="button primary" href="<%= new_admin_category_path %>">
  <span class="mif-plus"></span>
  Create...
</a>
<%= paginate @categories %>
<hr class="thin bg-grayLighter"></hr>
<% if @categories.any? %>
  <div class="dataTables_wrapper no-footer">
    <table class="dataTable border bordered no-footer" data-auto-width="false" data-role="" role="grid" aria-describedby="">
      <thead>
        <tr role="row">
          <td style="width: 20px" tabindex="0">ID</td>
          <td>Image</td>
          <td>Name</td>
          <td>Created At</td>
          <td>Updated At</td>
          <td>Operation</td>
        </tr>
      </thead>
      <tbody>
        <% @categories.each_with_index do |cat, idx| %>
          <tr class="<%= idx % 2 == 1 ? 'odd' : 'even' %>" role="row">
            <td><%= cat.id %></td>
            <td><%= image_tag(cat.image_url(:thumb)) %></td>
            <td><%= cat.name %></td>
            <td><%= cat.created_at.to_s(:db) %></td>
            <td><%= cat.updated_at.to_s(:db) %></td>
            <td>
              <%= link_to "Edit", edit_admin_category_path(cat) %>
              <%= link_to "Destroy", [:admin, cat], method: :delete, data: {confirm: 'Are you sure?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div>
    Sorry, there is no data.
  </div>
<% end %>
<%= paginate @categories %>

app/views/admin/categories/new.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% breadcrumb :articles %>
<div class='articles'>
  <div class="content">
    <% if @articles.any? %>
      <% @articles.each do |article| %>
        <div class="example"> <!-- data-text="blockquote" -->
          <blockquote>
            <p>
            <%= link_to article.title, article, "data-no-turbolink" => true %>
            </p>
            <small>
              <span class="mif-user"></span>
              <%= article.author_email %>&nbsp;
              <%= t("article.published_at", string: time_ago_in_words(article.created_at)) %>&nbsp;
              <% if article.category %>
                <span class="mif-tree"></span> 
                <%= link_to article.category.name, articles_path(category_id: article.category) %>&nbsp;
              <% end %>
              <% if article.tags.present? %>
                <span class="mif-tags"></span> 
                <%= article.tags.map { |ta| link_to ta.name, articles_path(tag: ta.name) }.join("&nbsp;").html_safe %>
              <% end %>
            </small>
          </blockquote>
          <hr class='thin'></hr>
        </div>
      <% end %>
    <% else %>
      <div class="example" style="text-align: center">
        Not Found!
      </div>
    <% end %>
  </div>
</div>

<%= paginate @articles, outer_window: 3 %>

app/views/articles/show.html.erb
<% breadcrumb :article, @article %>
<% content_for :assets do %>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
<% end %>
<div class="example">
  <div class="grid">
    <div class="row">
      <div class="cell">
        <ul class="step-list">
          <h3><%= @article.title %></h3>
          <h4 class="no-margin-top">
            <blockquote>
              <small>
                <span class="mif-user"></span>
                <%= t("article.published_at", string: time_ago_in_words(@article.created_at)) %>
                <% if @article.category %>
                  <span class="mif-tree"></span> 
                  <%= link_to @article.category.name, articles_path(category_id: @article.category) %>
                <% end %>
                <% if @article.tags.present? %>
                  <span class="mif-tags"></span> 
                  <%= sanitize @article.tags.map { |ta| link_to ta.name, articles_path(tag: ta.name) }.join("&nbsp;") %>
                <% end %>
              </small>
            </blockquote>
          </h4>
          <hr class="bg-red"></hr>
          <div class='example'>
            <%= sanitize(@article.body) %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- 多说最近访客 start -->
<ul class="ds-recent-visitors"></ul>
<!-- 多说最近访客 end -->
<!-- 多说评论框 start -->
<div class="ds-thread" data-thread-key="<%= @article.id %>" data-title="<%= @article.title %>" data-url="<%= article_url(@article) %>"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"tribe"};
(function() {
 var ds = document.createElement('script');
 ds.type = 'text/javascript';ds.async = true;
 ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
 ds.charset = 'UTF-8';
 (document.getElementsByTagName('head')[0] 
  || document.getElementsByTagName('body')[0]).appendChild(ds);
 })();
</script>
<!-- 多说公共JS代码 end -->

app/views/categories/index.html.erb
<% breadcrumb :categories %>
<div class="example" > <!-- data-text="Categories" -->
  <div class="grid no-margin-top">
    <% @categories.each_slice(@row_count).each do |group| %>
      <div class="row cells<%= @row_count %>">
      <% group.each do |category| %>
        <div class="cell">
          <h4><%= category.name %></h4>
          <div class="image-container">
            <div class="frame">
              <a href="<%= articles_path(category_id: category.id) %>"><%= image_tag(category.image_url(:normal)) %></a>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

<script>
$(function() {
    $(".image-container").hover(function() {
      $(this).addClass("element-selected");
    }, function() {
      $(this).removeClass("element-selected");
    });
});
</script>

app/views/layouts/_breadcrumb.html.erb
<%= breadcrumbs pretext: t('site.location'), separator: ' &rsaquo; ' %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="bottom-menu-wrapper">
    <ul class="horizontal-menu compact">
      <li><h4>&copy; 2016 Sven All Rights Reserved.</h4></li>
      <li class="place-right"><a href="mailto: sven199109@gmail.com"><%= t('site.contact') %></a></li>
      <li class="place-right"><a href="https://github.com/sven199109/tribe.git"><%= t('site.source_code') %></a></li>
      <li class="place-right"><a href="<%= about_path %>"><%= t("site.about") %></a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="margin20 no-margin-left no-margin-right">
  <div class="clear-float">
    <div class="place-right">
      <form action="<%= articles_path %>">
        <div class="input-control text margin20" style="width: 300px;">
          <input type="text" name="q" value="<%= params[:q] %>" placeholder="">
          <button class="button"><span class="mif-search"></span></button>
        </div>
      </form>
    </div>
    <a class='place-left' href='/' title=''>
      <h1><%= t('site.name') %></h1>
    </a>
  </div>

  <div class="main-menu-wrapper">
    <ul class='horizontal-menu' style='margin-left: -20px;'>
      <li><a href="<%= articles_path %>"><%= t('site.articles') %></a><li>
      <li><a href="<%= categories_path %>"><%= t('site.categories') %></a><li>
      <li><a href="<%= tags_path %>"><%= t('site.tags') %></a><li>
      <li><a href="<%= archive_path %>"><%= t('site.archives') %></a><li>
      <li><a href="<%= album_path %>"><%= t('site.albums') %></a><li>
      <li class='place-right'>
      <a href='#' class='dropdown-toggle'><%= t('site.multi_languages') %></a>
        <ul class='d-menu place-right' data-role='dropdown'>
          <li><a href='<%= locale_path(locale: :'zh-CN') %>'><%= t('site.chinese') %></a>
          <li><a href='<%= locale_path(locale: :ja) %>'><%= t('site.japanese') %></a>
        </ul>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/admin/_header.html.erb
<div class="app-bar fixed-top" data-role="appbar">
  <a class="app-bar-element branding" href="<%= admin_articles_path %>"><%= t('site.admin.name') %></a>
  <span class="app-bar-divider"></span>
  <ul class="app-bar-menu">
    <li data-flexorderorigin="0" data-flexorder="1">
    </li>
  </ul>
  <div class="app-bar-element place-right active-container">
    <span class="dropdown-toggle">
      <span class="mif-cog"></span>
      <%= current_user.email %>
    </span>
    <div class="app-bar-drop-container padding10 place-right no-margin-top block-shadow fg-dark" style="width: 220px; display: none;" data-no-close="true" data-role="dropdown">
      <ul class="unstyled-list fg-dark">
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'fg-white1 fg-hover-yellow'%>
        </li>
      </ul>
    </div>
    <div class="app-bar-pullbutton automatic" style="display: none;"></div>
    <nav class="app-bar-pullmenu hidden fixstyle-app-bar-menu" style="display: none;">
      <ul class="app-bar-pullmenubar hidden app-bar-menu"></ul>
    </nav>
  </div>
</div>

app/views/layouts/admin/_left.html.erb
<div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: 100%">
  <ul class="sidebar">
    <li class="<%= active?("admin/articles") %>">
      <a href="<%= admin_articles_path %>">
        <span class="mif-apps icon"></span>
        <span class="title">Articles</span>
        <span class="counter">
          <%= Article.count %>
        </span>
      </a>
    </li>
    <li class="<%= active?("admin/categories") %>">
      <a href="<%= admin_categories_path %>">
        <span class="mif-apps icon"></span>
        <span class="title">Categories</span>
        <span class="counter">
          <%= Category.count %>
        </span>
      </a>
    </li>
  </ul>
</div>

app/views/layouts/admin/_message.html.erb
<% if flash.any? %>
  <div class="grid">
    <div class="row cells4">
      <% flash.each do |k, v| %>
        <div class="notify <%= k %>">
          <span class="notify-closer"></span>
          <span class="notity-success"></span>
          <span class="notify-text">
            <%= v %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE>
<html>
<head>
  <title>Tribe Admin</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body class=''>
<%= render 'layouts/admin/header' %>
<div class="page-content">
  <div class="flex-grid no-responsive-future" style="height: 100%;">
    <div class="row" style="height: 100%">
      <%= render 'layouts/admin/left' %>
      <div class="cell auto-size padding20 bg-white" id="cell-content">
        <%= render 'layouts/admin/message' %>
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tribe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :assets %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/breadcrumb' %>
    <%= render 'layouts/admin/message' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<% breadcrumb :about %>
<div class='example'>
  Developing.
</div>

app/views/welcome/album.html.erb
<% breadcrumb :album %>
<div class='example'>
  Album is being developed, please wait.
</div>

app/views/welcome/archive.html.erb
<% breadcrumb :archive %>

<div class="example">
  <div class="cell">
    <% if archive_dates.any? %>
      <ul class="numeric-list large-bullet red-bullet">
        <% archive_dates.each do |date| %>
          <li><%= link_to date["created_at"], articles_path(pub_date: date["created_at"]) %>(<%= date["cnt"] %>)</li>
        <% end %>
      </ul>
    <% else %>
      <div>
        No Data.
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/tags.html.erb
<% breadcrumb :tags %>

<div class="example">
  <div class="grid no-margin-top">
    <% if all_tags.any? %>
      <% all_tags.each_slice(4) do |tags| %>
        <div class="row cells4">
          <% tags.each do |ta| %>
            <% next if ta.nil? %>
            <div class="cell">
              <% color = tag_color(ta) %>
              <a href="<%= articles_path(tag: ta.name) %>" class="button <%= color %> block-shadow-<%= color %> text-shadow"><%= ta.name %>(<%= articles_count_of_tag(ta) %>)</a>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div style='text-align: center'>No Data Found.</div>
    <% end %>
  </div>
</div>